### ISSUE TITLE
outline-cli: failed to create OutlineDevice: failed to create TCP dialer: failed to decode host string: illegal base64 data at input byte 7

### ISSUE THREAD

**Issue by jeffangelion** [Kir-Antipov/outline-cli#6]
## Error message

`/usr/local/bin/outline-cli: failed to create OutlineDevice: failed to create TCP dialer: failed to decode host string [ss://REDACTED]: illegal base64 data at input byte 7`

**Comment by jeffangelion** [comment]
If you need a test key, feel free to use this (note: it's missing URI beginning and has extra spaces)

`Y2hhY2hhMjAtaWV0Zi1          wb2x5MTMwNTo yMXdvd2pybTZ4d1d4c 2M5TVlkdEN5UFZM         WFZGQVl1QlF   IaWhGM1Z1NFF Md0NYQXZDdVlXUFh1TnBVZ       2NrWEp1Q2p4b1pFa213c2M1NFNFa3JD                     cE4ycER2               REdiY05XQlFAc3VwcG9      ydC50aGluc2Fua                                           mF5Lm1vbnN0ZXI6NTk1Njc                                                                    #160+%D0%94%D0%B5%D1%80%D0%B7%D0%BA%D0%B8%D0%B9+%D0%92%D0%B8%D0%B7%D0%B5%D0%BB%D1%8C`

**Comment by Kir-Antipov** [comment]
Thanks for reporting this!

The amount of data stored in your key doesn't fit perfectly into 3-byte chunks of Base64, resulting in the addition of a padding character *(i.e., "=")* during its conversion to the "modern" format, which, it turns out, doesn't need that. However, despite it being 2024, humanity still [hasn't figured out](https://github.com/Jigsaw-Code/outline-sdk/blob/888e11d1479d10da24e6e1abaec29f26b610f24e/x/config/shadowsocks.go#L99-L103) a way to strip unwanted padding from a **static** Base64 string:

```go
decoded, err := base64.URLEncoding.WithPadding(base64.NoPadding).DecodeString(url.Host)
if err != nil {
  // If decoding fails, return the original url with error
  return nil, fmt.Errorf("failed to decode host string [%v]: %w", url.String(), err)
}
```

Let me fix this real quick.
