### ISSUE TITLE
After connecting to outline, the connection via SSH is interrupted

### ISSUE THREAD

**Issue by andreydegt** [Kir-Antipov/outline-cli#8]
Subj

**Comment by Kir-Antipov** [comment]
This is to be expected. If you try to connect to a VPN mid-session, it will result in asymmetric routing, which may *(and usually does)* cause some network devices along the way to simply discard the packets. This is just how things are, so I don't think there's something to be done here.

However, you can easily configure the routing on your machine to your liking! If you don't require a VPN to connect to your server, you may as well inform your system about that:

```bash
sudo ip rule add from all to <ip-of-the-target-machine> table main priority 23331
```

Hope this helps! :)

**Comment by andreydegt** [comment]
"sudo ip rule add from all to <ip-of-the-target-machine> table main priority 23331"
Unfortunately it didn't work.
There are no such problems with the official client  Outline-Client.AppImage.  But it cannot be controlled via SSH and cli.

**Comment by Kir-Antipov** [comment]
Apologies for the late response!

> Unfortunately it didn't work.

That's strange - it consistently works on my machine. The only thing is that this solution isn't persistent. Did you happen to reboot between attempts? Also, which distro are you using?

**Comment by maxixcom** [comment]
The same problem is here. After enabling vpn all inbound connections to the server are unavailable.

**Comment by Kir-Antipov** [comment]
Could you please describe your issue in more detail and explain how it can be reproduced?

**Comment by maxixcom** [comment]
> Could you please describe your issue in more detail and explain how it can be reproduced?

You have
1 Remote server
2 Your Workstation

You need to run `outline-cli` on `Remote server` so applications on the server can make outgoing connection through ‘vpn’.
So you do on `your workstation` (suppose outline-cli is already installed on the `remote server`):

```
<local>$ ssh <remote server>
<remote>$ vpn connect 1
```

After vpn is up you can’t connect your `remote server` from `your workstation` until you somehow make vpn disconnected. That is the big problem.

PS: And another problem I found is when restarting server Network Manager make the connection up that make is much harder to make the `remote server` connectable - nice trap :)

**Comment by Kir-Antipov** [comment]
Oh, yikes. I sincerely hope the `remote server` here is a test machine and that this didn't happen to your production server or anything critical! If it did, you'll need to detach the storage disk from your server *(hopefully, your cloud provider allows this)*, attach it to a temporary droplet, chroot into it, and `rm /var/lib/outline/session` to bring the machine back to life.

Okay, back to the issue at hand. `outline-cli` redirects all of your traffic to the VPN server. Based on the limited feedback I have, the Outline Client works a bit differently in this regard and uses split tunneling somewhere along the way *(I couldn't test it myself since the Outline Client only seems to work on Ubuntu, and maybe Debian)*. I'm not sure if it uses allowlists or denylists, but in our case, it's more natural to go with the latter. I already have rules in place to block requests to the LAN from being forwarded *(fun fact: for better or worse, I forgot to make them persistent, so they only work until the first reboot)*. However, it's not as simple with "SSH requests", as they aren't as easily identifiable.

The simplest solution I suggested to the author of this issue was to hardcode the IP of the target machine to prevent redirection and avoid asymmetric routing. Unfortunately, that didn't work for them for some reason. Maybe I misread their problem, and they were also trying to connect their server to a VPN instead of their desktop.

However, hardcoding IPs clearly isn't a viable long-term solution for a server that could theoretically accept requests from any machine in the world. In this scenario, we could try identifying SSH traffic by the port it uses, which is typically port 22 *(though some people tend to change it, thinking this makes their machine more "secure")*. To do this, we can first mangle all the traffic traveling through that port and attach a special mark to it so we can identify it later:

```bash
# SSH doesn't use UDP for anything, at least anymore, so TCP rules should suffice
iptables -t mangle -A PREROUTING -p tcp --dport 22 -j MARK --set-mark 22
iptables -t mangle -A OUTPUT -p tcp --sport 22 -j MARK --set-mark 22
```

Then, we can exclude this marked traffic from being rerouted by running:

```bash
ip rule add fwmark 22 table main priority 23331
```

You can check if this works for you *(please, don't try this on a production server in case something doesn't work right the first time! :))*

However, note that these rules **ARE NOT PERSISTENT**! They'll be lost as soon as the machine reboots. So, you'll need to run these commands every time the server starts to ensure you can connect to it afterward.

Since I need to fix the LAN rerouting issue anyway, I could create a better config for `outline-cli` that would allow you to specify which traffic should be exempt from rerouting. By default, it might include the following rules:

```ignore
# LAN
192.168.0.0/16
172.16.0.0/12
10.0.0.0/8

# TUN
!10.233.233.1
!10.233.233.2

# SSH
:22
```

If someone needs to add their own rules, for example, if they've changed their SSH port, they'll be able to do so easily. How does that sound?

**Comment by maxixcom** [comment]
@Kir-Antipov I'm not an expert in all that network staff :) As I understand we will have the config where we can exclude traffic by networks or by protocols(like ssh) from rerouting them to 'vpn'. If this is correct then it sounds good. 

ps: In spite of all this obstacles, thank you for your attempt to make outline-cli more friendly.
